### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by count0** [conda-forge/graph-tool-feedstock#15]
Currently the build is failing due to Python 2 incompatibility. I can patch it, but my plan was to make the current release (2.30) the last one supporting Python 2. But it might be easier just to drop it, since this has already happened with matplotlib, scipy, numpy, etc.

**Comment by stuarteberg** [comment]
Either option is fine with me.

As of [last week][1], conda-forge has officially deprecated Python 2.7.  I think the next time we "rerender" this package, Python 2.7 support will be dropped automatically, unless we explicitly add it back.  It would be possible to maintain a Python 2 build for just a little longer, since [existing packages will not be deleted][2] (just not maintained).  Whatever you prefer is fine with me.

[1]: https://conda-forge.org/docs/user/announcements.html#id1
[2]: https://gitter.im/conda-forge/conda-forge.github.io?at=5e73e282f5b9723ad9ae09f0

**Comment by stuarteberg** [comment]
As a separate matter: The typical practice for maintaining conda-forge feedstocks is to avoid pushing to the master branch directly.  Instead, we always open a PR, even for relatively trivial changes.  (I have been gently scolded for this in the past, so now I've fallen in line 😄 )

So, do you mind if I open a new PR for the 2.30 upgrade?  (I'll start by reverting the master branch via force-push, then I'll use your recent commits as the basis for the PR.) We can discuss build issues in that thread. We'll also be able to make requests to the conda-forge admin bot, if necessary.

**Comment by count0** [comment]
Ok, so let's just drop python 2. It's a good idea anyway.

I'm sorry for pushing to master directly, I did it by mistake. I was using the github interface, and after a few revisions I pressed the wrong button in the end... I'll be more careful next time.

Please feel free to revert and open a PR.

**Comment by stuarteberg** [comment]
>Please feel free to revert and open a PR.

Done!

>I'm sorry for pushing to master directly, I did it by mistake.

Ah, sorry for the lecture, then.  But while I'm at it, I'll point out a non-obvious conda-forge rule: they [ask us not to create temporary branches][1] on the main repo -- we are supposed to use our own fork as the basis for all PRs.  The only permissible branches are the `master` branch, and any long-term maintenance branches we wish to be built built (and published) by the conda-forge CI.

Accordingly, I've deleted today's temporary branches from this repo.

[1]: https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Comment by count0** [comment]
Ok, thanks for the info. This was my first contribution to conda-forge ever, and did not bother to read anything, so my bad.
